/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}", // Quét tất cả các file trong thư mục src
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb596",
        "background": "#faf8ff",
        "tertiary-container": "#bc4800",
        "error": "#ba1a1a",
        "primary": "#004ac6",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e1e2ed",
        "secondary-fixed": "#dae2fd",
        "on-primary": "#ffffff",
        "surface-container": "#ededf9",
        "on-background": "#191b23",
        "surface-variant": "#e1e2ed",
        "on-primary-container": "#eeefff",
        "on-primary-fixed-variant": "#003ea8",
        "outline-variant": "#c3c6d7",
        "on-tertiary-fixed": "#360f00",
        "inverse-on-surface": "#f0f0fb",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-secondary-container": "#5c647a",
        "on-tertiary-container": "#ffede6",
        "secondary-container": "#dae2fd",
        "on-secondary-fixed-variant": "#3f465c",
        "on-secondary-fixed": "#131b2e",
        "surface-container-low": "#f3f3fe",
        "on-surface": "#191b23",
        "primary-container": "#2563eb",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#00174b",
        "secondary": "#565e74",
        "outline": "#737686",
        "surface": "#faf8ff",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary": "#ffffff",
        "surface-tint": "#0053db",
        "on-surface-variant": "#434655",
        "on-tertiary-fixed-variant": "#7d2d00",
        "inverse-primary": "#b4c5ff",
        "inverse-surface": "#2e3039",
        "on-error-container": "#93000a",
        "tertiary": "#943700",
        "tertiary-fixed": "#ffdbcd",
        "surface-bright": "#faf8ff",
        "secondary-fixed-dim": "#bec6e0",
        "surface-dim": "#d9d9e5",
        "surface-container-high": "#e7e7f3"
      },
      fontFamily: {
        "display": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "3xl": "64px",
        "container-max": "1280px",
        "base": "4px",
        "md": "16px",
        "sm": "8px",
        "xl": "32px",
        "lg": "24px",
        "2xl": "48px",
        "gutter": "24px"
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "display": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}

